[system]

dirpath = '../0.data/'
name = 'ProDOT-2Hex-00PC-cryst.xyz'

n_frame = 1000

[descriptor]

type = 'soap'
cutoff = 6.0
cutoff_transition_width = 1.0
n_max = 8
l_max = 4
atom_sigma = 0.5
n_Z = 1
Z = '{3}'
n_species = 5
species_Z = '{1 3 6 8 16}'