[system]

dirpath = '../0.data/traj/'
name = 'traj_2.1_0-1000.xyz'

n_frame = 1000
every = 5
saveFile = true
outheader = ''

[descriptor]
type = 'soap'
cutoff = 4.5
cutoff_transition_width = 1.0
n_max = 8
l_max = 4
atom_sigma = 0.5
n_Z = 1
Z = '{3}'
n_species = 6
species_Z = '{1 3 6 8 9 15}'
