[system]

dirpath = '../0.data/'
name = 'test_traj_10frames.xyz'

n_frame = 10
every = 2
saveFile = true
outheader = 'test'

[descriptor]
type = 'soap'
cutoff = 6.0
cutoff_transition_width = 1.0
n_max = 8
l_max = 4
atom_sigma = 0.5
n_Z = 1
Z = '{15}'
n_species = 6
species_Z = '{1 3 6 8 9 15}'
